script:
- npm install --no-save @takram/planck-core
- npm run test
language: node_js
node_js:
- 8.1
notifications:
  slack:
    secure: Q0wLRGKiX3T9wvLDjBjzUY3M0IXipXML2pLSpvxa8PGn8x83TP0Ik7B7UGfyvnmfdld14VcvhwhKH+vSfFC5E3bTKDw6+HWYYd0ouy5n691bs0SD8ztV99xlvpnK4hisgSJ3F6w2blGeVhf04BOJVlBsQBxQ5Y0iooFHsIoy5k9qYVCTKfy9K0ywFVELmMl9L6mcqsbSL8H40fKKXITYGevRpZIpAqnod+5UkyLRodL7UDTfeLncYWahNdWDUH6qll3aVF3PKtW/NM+jKrirRQlfTlC8K6S5RwrEyDMBQ13UQAYgCLvUrqIfHYVgyh7Tzb7ILF677KMpPu9o9uAWpS8zAp/JkwLby58jbpnSrV5hYZNuGu5NwKSDmfvxjz4T6gNZXSm+gL+Q1mMimLhznTifehEM7VU8PSI/RH2GHpBaYaIIb2LU+jomc5eZ2d8GlaHD58wFZ45e8ALZ1NQdTfIhTHKdJ4Ngx+qrQesZ1TUmiHTKJn7aJo8RGec16aiakOaKCclCgzBLQ2wRGGSwt8mqX2HBngj240JZVfD5pjM9DG152cYzWWQt1GB9nQT9zLxpKbDFQoVHWg/U20MZ9akwpONv0SfzzPGCcXvthXjx9F76R8yXkWDBxF6IrRgkr5gr3NzG8whowDLB/t6GPmmbvrelz20LK0VJrwR/KxY=
